name: "Request Review For Team"
author: acq688, myles2007
description: Assign reviews to individuals or teams based on the pr's author or author team.
branding:
  icon: user-check
  color: purple
inputs:
  GITHUB_TOKEN:
    description: "Github token"
    required: true
  config:
    description: "Configuration file"
    required: true
    default: ".github/request-review-for-team.yml"
runs:
    using: 'node12'
    main: 'index.js'
